const users = [
  {
    name: 'AdminUser',
    email: 'admin@havenproject.com',
    password: '123456',
    role: 'admin',
  },
  {
    name: 'Ana Silva',
    email: 'ana@example.com',
    password: '123456',
    role: 'buyer',
  },
  {
    name: 'Carlos Mendes',
    email: 'carlos@example.com',
    password: '123456',
    role: 'buyer',
  },
  {
    name: 'Lucia Torres',
    email: 'lucia@example.com',
    password: '123456',
    role: 'buyer',
  },
  {
    name: 'Mateo Rojas',
    email: 'mateo@example.com',
    password: '123456',
    role: 'buyer',
  },
];

const artisans = [
  {
    name: "Maria Souza",
    location: "Brazil",
    bio: "Ceramic artist inspired by nature.",
    email: "mariasouza@havenartisans.com",
    image_url: "/artisans/maria-souza.jpg",
  },
  {
    name: "Diego Ramos",
    location: "Mexico",
    bio: "Leather craftsman with 10 years experience.",
    email: "diegoramos@havenartisans.com",
    image_url: "/artisans/diego-ramos.jpg",
  },
  {
    name: "Aiko Tanaka",
    location: "Japan",
    bio: "Minimalist woodworker.",
    email: "aikotanaka@havenartisans.com",
    image_url: "/artisans/aiko-tanaka.jpg",
  },
  {
    name: "Amara Okafor",
    location: "Nigeria",
    bio: "Textile artist specializing in woven designs.",
    email: "amaraokafor@havenartisans.com",
    image_url: "/artisans/amara-okafor.jpg",
  },
  {
    name: "Lucas Pereira",
    location: "Brazil",
    bio: "Metal sculptor creating modern art.",
    email: "lucaspereira@havenartisans.com",
    image_url: "/artisans/lucas-pereira.jpg",
  },
  {
    name: "Isabella Rossi",
    location: "Italy",
    bio: "Glass jewelry designer.",
    email: "isabellarossi@havenartisans.com",
    image_url: "/artisans/isabella-rossi.jpg",
  },
  {
    name: "Noah Kim",
    location: "South Korea",
    bio: "Ceramic tableware expert.",
    email: "noahkim@havenartisans.com",
    image_url: "/artisans/noah-kim.jpg",
  },
  {
    name: "Fatima Zahra",
    location: "Morocco",
    bio: "Traditional rug weaver.",
    email: "fatimaza@havenartisans.com",
    image_url: "/artisans/fatima-zahra.jpg",
  },
  {
    name: "Ethan Walker",
    location: "USA",
    bio: "Wood carving specialist.",
    email: "ethanwalker@havenartisans.com",
    image_url: "/artisans/ethan-walker.jpg",
  },
  {
    name: "Camila Duarte",
    location: "Colombia",
    bio: "Handmade accessories designer.",
    email: "camiladuarte@havenartisans.com",
    image_url: "/artisans/camila-duarte.jpg",
  },
  {
    name: "Luca Farfelli",
    location: "Denmark",
    bio: "Handmade accessories designer.",
    email: "lucafarfelli@havenartisans.com",
    image_url: "/artisans/luca-farfelli.jpg",
  },
  {
    name: "Juan Perez",
    location: "Peru",
    bio: "Handmade accessories designer.",
    email: "juanperez@havenartisans.com",
    image_url: "/artisans/juan-perez.jpg",
  },
];

const products = [
    {
        name: "Clay Vase",
        material: "Clay",
        price: 25,
        description: "Handmade clay vase.",
        image_url: "/products/clay-vase.png",
        artisanIndex: 0,
    },
    { 
        name: "Leather Wallet",
        material: "Leather",
        price: 40,
        description: "Durable leather wallet.",
        image_url: "/products/leather-wallet.png",
        artisanIndex: 1,
    },
    {
        name: "Wooden Bowl",
        material: "Wood",
        price: 30,
        description: "Minimalist wooden bowl.",
        image_url: "/products/wooden-bowl.png",
        artisanIndex: 2,
    },
    {
        name: "Glass Necklace",
        material: "Glass",
        price: 50,
        description: "Elegant glass necklace.",
        image_url: "/products/glass-necklace.png",
        artisanIndex: 5,
    },
    {
        name: "Woven Rug",
        material: "Textile",
        price: 120,
        description: "Handwoven rug.",
        image_url: "/products/woven-rug.png",
        artisanIndex: 3,
    },
    {
        name: "Metal Sculpture",
        material: "Metal",
        price: 200,
        description: "Abstract metal sculpture.",
        image_url: "/products/metal-sculpture.png",
        artisanIndex: 4,
    },
    {
        name: "Painted Earrings",
        material: "Ceramic",
        price: 20,
        description: "Colorful earrings.",
        image_url: "/products/painted-earrings.png",
        artisanIndex: 6,
    },
    {
        name: "Wood Mask",
        material: "Wood",
        price: 60,
        description: "Traditional carved mask.",
        image_url: "/products/wood-mask.png",
        artisanIndex: 7,
    },
    {
        name: "Ceramic Plate",
        material: "Ceramic",
        price: 35,
        description: "Decorative plate.",
        image_url: "/products/ceramic-plate.png",
        artisanIndex: 0,
    },
    {
        name: "Leather Belt",
        material: "Leather",
        price: 45,
        description: "Handmade belt.",
        image_url: "/products/leather-belt.png",
        artisanIndex: 1,
    },
    {
        name: "Handwoven Basket",
        material: "Textile",
        price: 55,
        description: "Eco-friendly woven basket.",
        image_url: "/products/handwoven-basket.jpg",
        artisanIndex: 3,
    },
    {
        name: "Stone Pendant",
        material: "Stone",
        price: 28,
        description: "Natural stone pendant necklace.",
        image_url: "/products/stone-pendant.jpg",
        artisanIndex: 5,
    },
    {
        name: "Ceramic Teapot",
        material: "Ceramic",
        price: 65,
        description: "Traditional handmade teapot.",
        image_url: "/products/ceramic-teapot.jpg",
        artisanIndex: 6,
    },
    {
        name: "Wooden Spoon Set",
        material: "Wood",
        price: 22,
        description: "Set of handcrafted wooden spoons.",
        image_url: "/products/wood-spoon-set.jpg",
        artisanIndex: 2,
    },
    {
        name: "Leather Journal",
        material: "Leather",
        price: 48,
        description: "Hand-stitched leather journal.",
        image_url: "/products/leather-journal.jpg",
        artisanIndex: 1,
    },
    {
        name: "Glass Vase",
        material: "Glass",
        price: 70,
        description: "Elegant blown glass vase.",
        image_url: "/products/glass-vase.jpg",
        artisanIndex: 5,
    },
    {
        name: "Wool Scarf",
        material: "Textile",
        price: 35,
        description: "Warm handmade wool scarf.",
        image_url: "/products/wool-scarf.jpg",
        artisanIndex: 3,
    },
    {
        name: "Clay Incense Holder",
        material: "Clay",
        price: 18,
        description: "Minimalist incense holder.",
        image_url: "/products/clay-incense-holder.jpg",
        artisanIndex: 0,
    },
    {
        name: "Metal Candle Holder",
        material: "Metal",
        price: 42,
        description: "Modern metal candle holder.",
        image_url: "/products/metal-candle-holder.jpg",
        artisanIndex: 4,
    },
    {
        name: "Wooden Picture Frame",
        material: "Wood",
        price: 30,
        description: "Rustic wooden frame.",
        image_url: "/products/wooden-picture-frame.jpg",
        artisanIndex: 8,
    },
    {
        name: "Beaded Bracelet",
        material: "Glass",
        price: 15,
        description: "Colorful handmade bracelet.",
        image_url: "/products/beaded-bracelet.jpg",
        artisanIndex: 9,
    },
    {
        name: "Ceramic Bowl Set",
        material: "Ceramic",
        price: 75,
        description: "Set of 3 ceramic bowls.",
        image_url: "/products/ceramic-bowl-set.jpg",
        artisanIndex: 6,
    },
    {
        name: "Leather Keychain",
        material: "Leather",
        price: 15,
        description: "Simple handmade keychain.",
        image_url: "/products/leather-keychain.jpg",
        artisanIndex: 1,
    },
    {
        name: "Wooden Jewelry Box",
        material: "Wood",
        price: 85,
        description: "Hand-carved jewelry box.",
        image_url: "/products/wooden-jewelry-box.jpg",
        artisanIndex: 2,
    },
    {
        name: "Decorative Wall Hanging",
        material: "Textile",
        price: 95,
        description: "Handwoven wall decoration.",
        image_url: "/products/decorative-wall-hanging.jpg",
        artisanIndex: 7,
    },
    {
        name: "Minimalist Leather Card Holder",
        material: "Leather",
        price: 32,
        description: "Slim handmade leather card holder.",
        image_url: "/products/minimalistic-leather-card-holder.jpg",
        artisanIndex: 10,
    },
    {
        name: "Nordic Wooden Lamp",
        material: "Wood",
        price: 110,
        description: "Scandinavian-style handcrafted lamp.",
        image_url: "/products/nordic-wooden-lamp.jpg",
        artisanIndex: 10,
    },
    {
        name: "Handcrafted Travel Pouch",
        material: "Textile",
        price: 38,
        description: "Compact pouch for travel essentials.",
        image_url: "/products/handcrafter-travel-pouch.jpg",
        artisanIndex: 11,
    },
    {
        name: "Andean Woven Bracelet",
        material: "Textile",
        price: 20,
        description: "Traditional Peruvian woven bracelet.",
        image_url: "/products/andean-woven-bracelet.jpg",
        artisanIndex: 11,
    },
    {
        name: "Decorative Ceramic Tile",
        material: "Ceramic",
        price: 27,
        description: "Hand-painted decorative tile.",
        image_url: "/products/decorative-ceramic-tile.jpg",
        artisanIndex: 11,
    }
];

const reviews =  [
  // Products 0–9 (original ones)
  { rating: 5, comment: "Amazing craftsmanship!", userIndex: 1, productIndex: 0 },
  { rating: 4, comment: "Very solid quality.", userIndex: 2, productIndex: 1 },
  { rating: 5, comment: "Beautiful and minimal.", userIndex: 3, productIndex: 2 },
  { rating: 4, comment: "Looks great on me.", userIndex: 4, productIndex: 3 },
  { rating: 5, comment: "Absolutely stunning rug.", userIndex: 1, productIndex: 4 },
  { rating: 5, comment: "A real statement piece.", userIndex: 2, productIndex: 5 },
  { rating: 4, comment: "Cute and colorful.", userIndex: 3, productIndex: 6 },
  { rating: 5, comment: "Very detailed carving.", userIndex: 4, productIndex: 7 },
  { rating: 4, comment: "Nice decorative plate.", userIndex: 1, productIndex: 8 },
  { rating: 5, comment: "Fits perfectly.", userIndex: 2, productIndex: 9 },

  // Products 10–19
  { rating: 4, comment: "Very practical basket.", userIndex: 3, productIndex: 10 },
  { rating: 5, comment: "Love the natural stone!", userIndex: 4, productIndex: 11 },
  { rating: 5, comment: "Perfect tea companion.", userIndex: 1, productIndex: 12 },
  { rating: 4, comment: "Nice kitchen addition.", userIndex: 2, productIndex: 13 },
  { rating: 5, comment: "Feels premium.", userIndex: 3, productIndex: 14 },
  { rating: 5, comment: "Elegant design.", userIndex: 4, productIndex: 15 },
  { rating: 4, comment: "Very warm and soft.", userIndex: 1, productIndex: 16 },
  { rating: 5, comment: "Minimal and stylish.", userIndex: 2, productIndex: 17 },
  { rating: 4, comment: "Modern look.", userIndex: 3, productIndex: 18 },
  { rating: 5, comment: "Great quality frame.", userIndex: 4, productIndex: 19 },

  // Products 20–24
  { rating: 4, comment: "Nice bracelet.", userIndex: 1, productIndex: 20 },
  { rating: 5, comment: "Perfect set!", userIndex: 2, productIndex: 21 },
  { rating: 4, comment: "Simple but useful.", userIndex: 3, productIndex: 22 },
  { rating: 5, comment: "Beautiful carving work.", userIndex: 4, productIndex: 23 },
  { rating: 5, comment: "Looks amazing on my wall.", userIndex: 1, productIndex: 24 },

  // Products 25–29 (new artisans 10 & 11 included)
  { rating: 5, comment: "Very sleek design.", userIndex: 2, productIndex: 25 },
  { rating: 4, comment: "Perfect Nordic vibe.", userIndex: 3, productIndex: 26 },
  { rating: 5, comment: "Great for travel.", userIndex: 4, productIndex: 27 },
  { rating: 5, comment: "Beautiful traditional work.", userIndex: 1, productIndex: 28 },
  { rating: 4, comment: "Lovely decorative piece.", userIndex: 2, productIndex: 29 },
];

export {users, reviews, products, artisans };